import createClient, { type Client } from 'openapi-fetch';
import { env } from './env.js';
// Generated by `pnpm gen:types` from spec/glamer.openapi.yaml.
import type { paths } from '../spec/glamer.d.ts';

export type GlamerClient = Client<paths>;

/**
 * Typed API client over the OpenAPI spec. Pass a bearer token to make
 * authenticated calls; omit it for anonymous endpoints.
 */
export function makeApiClient(token?: string): GlamerClient {
  return createClient<paths>({
    baseUrl: env.apiBaseUrl,
    headers: token ? { Authorization: `Bearer ${token}` } : {},
  });
}
