import createClient, { type Client } from 'openapi-fetch';
import { env } from './env.js';
import { CookieJar, createCookieFetch } from './cookie-fetch.js';
// Generated by `pnpm gen:types` from spec/glamer.openapi.yaml.
import type { paths } from '../spec/glamer.d.ts';

export type GlamerClient = Client<paths>;

// The cookie name Glamer's cookieAuth scheme uses.
const SESSION_COOKIE = 'glamer-session';

// Each client owns a cookie jar; authenticate() reaches it via setSessionCookie().
const jars = new WeakMap<GlamerClient, CookieJar>();

/**
 * Typed API client over the OpenAPI spec, with its own cookie jar so the
 * `glamer-session` cookie persists across calls. Use `authenticate()`
 * (support/auth.ts) to establish a session on the client.
 */
export function makeApiClient(): GlamerClient {
  const jar = new CookieJar();
  const client = createClient<paths>({
    baseUrl: env.apiBaseUrl,
    fetch: createCookieFetch(jar),
  });
  jars.set(client, jar);
  return client;
}

/**
 * Set the session cookie on a client's jar. POST /session returns the session
 * value in its JSON body (SessionResponse.session), not a Set-Cookie header.
 */
export function setSessionCookie(client: GlamerClient, value: string): void {
  jars.get(client)?.set(SESSION_COOKIE, value);
}
