import createClient, { type Client } from 'openapi-fetch';
import { env } from './env.js';
import { createCookieFetch } from './cookie-fetch.js';
// Generated by `pnpm gen:types` from spec/glamer.openapi.yaml.
import type { paths } from '../spec/glamer.d.ts';

export type GlamerClient = Client<paths>;

/**
 * Typed API client over the OpenAPI spec, with its own cookie jar so the
 * `glamer-session` cookie set by POST /session persists across calls. Use
 * `authenticate()` (support/auth.ts) to establish a session on the client.
 */
export function makeApiClient(): GlamerClient {
  return createClient<paths>({
    baseUrl: env.apiBaseUrl,
    fetch: createCookieFetch(),
  });
}
